"""API key checking.

The service stores only the SHA-256 of the key, so reading the deployed secret does not
let you call the service. Keys are generated by `python -m ytdl_rest keygen`, which means
they carry full random entropy and a plain digest is enough; a slow KDF exists to make
guessable human passwords expensive to attack, which is not the situation here.
"""

from __future__ import annotations

import hashlib
import secrets

KEY_BYTES = 32


def generate_key() -> str:
    """A new API key. Enough entropy that the digest cannot be attacked by guessing."""
    return secrets.token_urlsafe(KEY_BYTES)


def hash_key(key: str) -> str:
    return hashlib.sha256(key.encode()).hexdigest()


def verify(key: str | None, expected_hash: str | None) -> bool:
    """True when the key matches. No key configured means the service is open."""
    if expected_hash is None:
        return True
    if not key:
        return False
    # Constant time, so a wrong key cannot be refined by measuring how long the
    # comparison took.
    return secrets.compare_digest(hash_key(key), expected_hash)
